# Generated by Django 5.2.7 on 2025-12-14 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='')),
                ('major', models.CharField(blank=True, default='', max_length=100)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('year', models.CharField(blank=True, default='', max_length=20)),
                ('workplace', models.CharField(blank=True, default='', max_length=200)),
                ('hometown', models.CharField(blank=True, default='', max_length=200)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
